# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fftabs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fftabs(object):
    def setupUi(self, fftabs):
        fftabs.setObjectName("fftabs")
        fftabs.resize(1015, 630)
        self.verticalLayout = QtWidgets.QVBoxLayout(fftabs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(fftabs)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnloadsess = QtWidgets.QPushButton(fftabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnloadsess.sizePolicy().hasHeightForWidth())
        self.btnloadsess.setSizePolicy(sizePolicy)
        self.btnloadsess.setObjectName("btnloadsess")
        self.horizontalLayout.addWidget(self.btnloadsess)
        self.btnsavesess = QtWidgets.QPushButton(fftabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsavesess.sizePolicy().hasHeightForWidth())
        self.btnsavesess.setSizePolicy(sizePolicy)
        self.btnsavesess.setObjectName("btnsavesess")
        self.horizontalLayout.addWidget(self.btnsavesess)
        self.linklabel = QtWidgets.QLabel(fftabs)
        self.linklabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linklabel.setOpenExternalLinks(True)
        self.linklabel.setObjectName("linklabel")
        self.horizontalLayout.addWidget(self.linklabel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(fftabs)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fftabs)

    def retranslateUi(self, fftabs):
        _translate = QtCore.QCoreApplication.translate
        fftabs.setWindowTitle(_translate("fftabs", "FindFunc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("fftabs", "Tab 1"))
        self.btnloadsess.setText(_translate("fftabs", "load session"))
        self.btnsavesess.setText(_translate("fftabs", "save session"))
        self.linklabel.setText(_translate("fftabs", "ff"))
